version: 2.1

executors:
  node-lts:
    parameters:
      class:
        description: The resource class
        type: enum
        enum: [ 'small', 'medium', 'large', 'xlarge' ]
        default: 'medium'
    docker:
      - image: circleci/node:lts-stretch
    resource_class: <<parameters.class>>

jobs:
  install:
    executor:
      class: small
      name: node-lts
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save NPM cache
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint-test:
    executor:
      class: small
      name: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run CommitLint
          command: npm run lint:commit
      - run:
          name: Run Prettier and ESLint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test:coverage -- --ci --runInBand

  build:
    executor:
      class: medium
      name: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2.1
  validate:
    jobs:
      - install
      - lint-test:
          requires:
            - install
      - build:
          requires:
            - install
