version: 2.1

orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.4

jobs:
  install:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save NPM cache
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint-test:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test:coverage -- --ci --runInBand

  build:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2.1
  validate:
    jobs:
      - install
      - lint-test:
          requires:
            - install
      - build:
          requires:
            - install
