version: 2.1

orbs:
  secrethub: secrethub/cli@1.1

executors:
  node-lts:
    parameters:
      class:
        description: The resource class
        type: enum
        enum: [ 'small', 'medium', 'large', 'xlarge' ]
        default: 'medium'
    docker:
      - image: circleci/node:lts-stretch
    resource_class: <<parameters.class>>

jobs:
  install:
    executor:
      class: small
      name: node-lts
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save NPM cache
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint-test:
    executor:
      class: small
      name: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run CommitLint
          command: npm run lint:commit
      - run:
          name: Run Prettier and ESLint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test:coverage -- --ci --runInBand

  build:
    executor:
      class: medium
      name: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: NODE_OPTIONS=--max_old_space_size=3072 npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - storybook-static

  chromatic:
    executor:
      class: medium
      name: node-lts
    environment:
      CHROMATIC_PROJECT_TOKEN: 'secrethub://graviteeio/cicd/graviteebot/chromatic_project_token'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - secrethub/exec:
          step-name: Running Chromatic
          command: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded -d=storybook-static

workflows:
  version: 2.1
  validate:
    jobs:
      - install
      - lint-test:
          requires:
            - install
      - build:
          requires:
            - install
      - trigger-chromatic:
          type: approval
          requires:
            - build
          # Ignore this manual step and trigger chromatic automatically on `master`
          filters:
            branches:
              ignore: master
      - chromatic:
          context: gravitee-qa
          requires:
            - build
            - trigger-chromatic
